#!/usr/bin/env ruby
base_path = File.expand_path("../lib", __dir__)

if File.exist? base_path
    require_relative "../lib/rubidex"
    require "pry-byebug"
else
    require "rubidex"
end

Rubidex::Tools::Tags.execute(ARGV)